### ISSUE TITLE
Creation EVALUATION.md

### ISSUE THREAD

**Issue by theo-lev** [sabari2018/PDL_2020-2021_GR5#9]
- [x] Compare success rate for HTML and WikiText extractor
- [x] Criticism of the existing : elements missing

**Comment by theo-lev** [comment]
Sur les 336 url donnés j'en ai 303 de traités et je trouve 1657 tableau traités en HTML, 1049 en WikiText.
Among the table not treaty, most problems come from the fact that the url does not exist anymore or the url was rename

**Comment by alecler** [comment]
**Extractor upgrate :**

HTML : 
Test comparison_between_Esperanto_and_Ido_3 :
 -> Bad extract of headers of rows
 -> Merged cells create a new column for each rows 
 -> When cells are merged, only one row include the value
Test comparison_between_Esperanto_and_Ido_2 :
 -> When the value of cells is a link, it extract the content

Wikitext : 
Test comparison_between_Esperanto_and_Ido_3 :
-> Merged cells create a new column for each rows
-> When cells are merged, only one row include the value
Test comparison_between_Esperanto_and_Ido_6 :
-> Some cells in colors extract the color attribute (style = background...) 
Comparison_of_ADC_software_2 : 
-> "?" replace by "dunno"
Comparison_of_document_interfaces_1 : 
-> When they are a link in exponent, it extract the date of the article of the link
Comparison_of_relational_database_management_7 : 
-> Some title of row were shifted or delete
Comparison_of_European_road_signs_2 : 
-> When they are a picture in a cell, it extract her size (in html it was the link of the picture --> better)
